#!/usr/bin/env bash
#
# Generate an Xcode project that a *free* Apple ID can install on a phone.
#
# Two things in `project.yml` need a paid Apple Developer Program membership, and neither is
# part of the product:
#
#   * the App Group. Only the widgets use it — the app writes a small snapshot there so the
#     Home Screen tile has something to draw without photo library access of its own. A free
#     personal team cannot create App Groups at all, and Xcode refuses to sign a build that
#     asks for one.
#   * the bundle identifiers. `com.gorkemgur.*` belongs to somebody. Yours has to be yours, or
#     Xcode will tell you the identifier is unavailable.
#
# So this writes `project.personal.yml` with the App Group stripped and the identifiers
# re-prefixed, and generates `DupeSpace.xcodeproj` from that. Everything the app actually does
# — scan, compare, budget, delete, receipt — is untouched. The widgets install and run; they
# show their "nothing yet" state, because the snapshot store returns nil without the group and
# every caller already draws a placeholder rather than inventing numbers.
#
#   ./Scripts/for-my-phone.sh com.yourname
#
# Re-run `xcodegen` on its own to go back to the real project.
set -euo pipefail
cd "$(dirname "$0")/.."

PREFIX="${1:-}"
if [ -z "$PREFIX" ]; then
  echo "usage: $0 <your reverse-domain prefix, e.g. com.gorkem>" >&2
  echo "it has to be unique to you — Apple hands each identifier to one account only." >&2
  exit 2
fi

python3 - "$PREFIX" <<'PY'
import re, sys

prefix = sys.argv[1]
spec = open("project.yml").read()

# The App Group, in both targets. Anchored on the two lines that follow the key so a change to
# the identifier or to the surrounding keys fails here rather than silently leaving it in.
block = """    entitlements:
      path: DupeSpace/DupeSpace.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.gorkemgur.dupespace
"""
widget_block = """    entitlements:
      path: DupeSpaceWidgets/DupeSpaceWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.gorkemgur.dupespace
"""
missing = [name for name, text in (("app", block), ("widget", widget_block)) if text not in spec]
if missing:
    sys.exit("project.yml no longer holds the %s App Group block this script removes — "
             "update Scripts/for-my-phone.sh" % " and ".join(missing))

spec = spec.replace(block, "").replace(widget_block, "")

# The identifiers, including `bundleIdPrefix` and the URL scheme's own name.
if "com.gorkemgur" not in spec:
    sys.exit("project.yml no longer uses the com.gorkemgur prefix — update this script")
spec = spec.replace("com.gorkemgur", prefix)

header = (
    "# GENERATED by Scripts/for-my-phone.sh — do not edit, and do not commit.\n"
    "# The App Group is stripped and the identifiers are re-prefixed so a free Apple ID can\n"
    "# sign this. `project.yml` is the real one.\n"
)
open("project.personal.yml", "w").write(header + spec)
print("wrote project.personal.yml with prefix %s" % prefix)
PY

xcodegen generate --spec project.personal.yml
echo
echo "Done. Now:"
echo "  1. open DupeSpace.xcodeproj"
echo "  2. select the DupeSpace target, Signing & Capabilities, and pick your own Apple ID team"
echo "  3. do the same for DupeSpaceWidgets"
echo "  4. plug the phone in, pick it in the scheme, press Run"
echo
echo "A free team's provisioning lasts seven days. When the app stops opening, press Run again."
